# Dependencies
markdown:         redcarpet
pygments:         true
highlighter:      pygments

kramdown:
  input: GFM

# Permalinks
permalink:        pretty

# Setup
title:            Regin
tagline:          'gudarnas återkomst'
description:      'Du är Regin, ett gudomligt väsen som har kraft att forma världarna. Regin - Lajvet för kreativa spelare som vill forma sin karaktärs och världens utveckling.'
url:              http://regin.mumma.nu
baseurl:          '/'

paginate:         5
paginate_path:    "blog/page:num"
banner:           banner.jpg

author:
  name:           'Patrik'
  url:            https://www.mumma.nu

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/paven/regin

gems:
- jekyll-mentions
- jekyll-sitemap

first_page:
  url: inledning
