# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            JekyllTalk
tagline:          'Blogging like a programmer'
description:      ''
url:              http://www.mumma.nu/jekyllTalk
baseurl:          '/jekyllTalk'
paginate:         5

author:
  name:           'Patrik Gustafsson'
  url:            https://twitter.com/paven

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/paven/jekyllTalk
