# Dependencies
markdown:         redcarpet
highlighter:      pygments

kramdown:
  input: GFM

# Permalinks
permalink:        pretty

# Setup
title:            JekyllTalk
tagline:          'Blogging like a programmer'
description:      ''
url:              http://www.mumma.nu/jekyllTalk/
baseurl:          '/jekyllTalk/'
first_page:		  inledning

paginate:         5
paginate_path:    "blog/page:num"
banner:           banner.jpg

author:
  name:           'Patrik'
  url:            https://www.mumma.nu

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/paven/jekyllTalk

gems:
- jekyll-mentions
- jekyll-sitemap

